import 'server-only';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { and,asc,eq,desc,gte,lte,sql } from 'drizzle-orm';
import { tokens,dailyMetrics,exercises,meta,healthRecords,syncState,foodLogs,dailyScores,dataQuality,timelineEvents,journalEntries,strengthSessions,strengthSets,coachThreads,coachMessages,writeOperations } from '../../drizzle/schema';
import {decryptSecret,encryptSecret} from './crypto';

const globalForDb=globalThis as unknown as {pool?:Pool};
const pool=globalForDb.pool??new Pool({connectionString:process.env.DATABASE_URL});
if(process.env.NODE_ENV!=='production')globalForDb.pool=pool;
export const db=drizzle(pool);
export async function getTokens(){const row=(await db.select().from(tokens).where(eq(tokens.id,1)).limit(1))[0];if(!row)return undefined;if((row.accessToken&&!row.accessToken.startsWith('enc:v1:'))||(row.refreshToken&&!row.refreshToken.startsWith('enc:v1:')))await db.update(tokens).set({accessToken:encryptSecret(row.accessToken),refreshToken:encryptSecret(row.refreshToken),updatedAt:Date.now()}).where(eq(tokens.id,1));return {...row,accessToken:decryptSecret(row.accessToken),refreshToken:decryptSecret(row.refreshToken)}}
export async function saveTokens(v:{accessToken:string;refreshToken?:string|null;expiry:number;scope?:string|null}){const old=await getTokens(),accessToken=encryptSecret(v.accessToken),refreshToken=encryptSecret(v.refreshToken??old?.refreshToken??null);await db.insert(tokens).values({id:1,accessToken,refreshToken,expiry:v.expiry,scope:v.scope??null,updatedAt:Date.now()}).onConflictDoUpdate({target:tokens.id,set:{accessToken,refreshToken,expiry:v.expiry,scope:v.scope??null,updatedAt:Date.now()}})}
export async function deleteTokens(){await db.delete(tokens).where(eq(tokens.id,1))}
export async function getDaily(metric:string,days:number){return (await db.select({date:dailyMetrics.date,value:dailyMetrics.value}).from(dailyMetrics).where(eq(dailyMetrics.metric,metric)).orderBy(desc(dailyMetrics.date)).limit(days)).reverse()}
export async function saveDaily(date:string,metric:string,value:number){await db.insert(dailyMetrics).values({date,metric,value,updatedAt:Date.now()}).onConflictDoUpdate({target:[dailyMetrics.date,dailyMetrics.metric],set:{value,updatedAt:Date.now()}})}
export async function getExercises(limit:number){return db.select().from(exercises).orderBy(desc(exercises.startTime)).limit(limit)}
export async function saveExercise(v:typeof exercises.$inferInsert){await db.insert(exercises).values(v).onConflictDoUpdate({target:exercises.id,set:v})}
export async function getMeta(key:string){return (await db.select().from(meta).where(eq(meta.key,key)).limit(1))[0]?.value??null}
export async function setMeta(key:string,value:string|number){await db.insert(meta).values({key,value:String(value)}).onConflictDoUpdate({target:meta.key,set:{value:String(value)}})}
export async function saveHealthRecord(v:typeof healthRecords.$inferInsert){await db.insert(healthRecords).values(v).onConflictDoUpdate({target:healthRecords.id,set:{dataType:v.dataType,startTime:v.startTime,endTime:v.endTime,date:v.date,numericValue:v.numericValue,payload:v.payload,updatedAt:v.updatedAt}})}
export async function saveHealthRecords(values:(typeof healthRecords.$inferInsert)[]){for(let i=0;i<values.length;i+=500){const chunk=values.slice(i,i+500);if(!chunk.length)continue;await db.insert(healthRecords).values(chunk).onConflictDoUpdate({target:healthRecords.id,set:{dataType:sql`excluded.data_type`,startTime:sql`excluded.start_time`,endTime:sql`excluded.end_time`,date:sql`excluded.date`,numericValue:sql`excluded.numeric_value`,payload:sql`excluded.payload`,updatedAt:sql`excluded.updated_at`}})}}
export async function saveDailyMetrics(values:{date:string;metric:string;value:number;updatedAt:number}[]){for(let i=0;i<values.length;i+=500){const chunk=values.slice(i,i+500);if(!chunk.length)continue;await db.insert(dailyMetrics).values(chunk).onConflictDoUpdate({target:[dailyMetrics.date,dailyMetrics.metric],set:{value:sql`excluded.value`,updatedAt:sql`excluded.updated_at`}})}}
export async function saveExercises(values:(typeof exercises.$inferInsert)[]){for(let i=0;i<values.length;i+=100){const chunk=values.slice(i,i+100);if(!chunk.length)continue;await db.insert(exercises).values(chunk).onConflictDoUpdate({target:exercises.id,set:{type:sql`excluded.type`,displayName:sql`excluded.display_name`,startTime:sql`excluded.start_time`,durationS:sql`excluded.duration_s`,calories:sql`excluded.calories`,distanceMm:sql`excluded.distance_mm`,steps:sql`excluded.steps`,avgHr:sql`excluded.avg_hr`,raw:sql`excluded.raw`,updatedAt:sql`excluded.updated_at`}})}}
export async function setSyncState(dataType:string,status:string,recordCount=0,error:string|null=null){await db.insert(syncState).values({dataType,status,recordCount,error,lastSyncedAt:status==='complete'?Date.now():null,updatedAt:Date.now()}).onConflictDoUpdate({target:syncState.dataType,set:{status,recordCount,error,lastSyncedAt:status==='complete'?Date.now():null,updatedAt:Date.now()}})}
export async function getSyncStates(){return db.select().from(syncState).orderBy(syncState.dataType)}
export async function getHealthRecords(dataType:string,limit=100){return db.select().from(healthRecords).where(eq(healthRecords.dataType,dataType)).orderBy(sql`date DESC NULLS LAST`,sql`start_time DESC NULLS LAST`).limit(limit)}
export async function getHealthCoverage(){return db.select({dataType:healthRecords.dataType,count:sql<number>`count(*)::int`,latest:sql<string>`max(coalesce(date,start_time))`}).from(healthRecords).groupBy(healthRecords.dataType).orderBy(healthRecords.dataType)}
export async function getFoodLogs(date?:string){return db.select().from(foodLogs).where(date?eq(foodLogs.date,date):undefined).orderBy(desc(foodLogs.date),desc(foodLogs.createdAt))}
export async function getFoodLog(id:string){return (await db.select().from(foodLogs).where(eq(foodLogs.id,id)).limit(1))[0]}
export async function saveFoodLog(v:typeof foodLogs.$inferInsert){return (await db.insert(foodLogs).values(v).returning())[0]}
export async function deleteFoodLog(id:string){return db.delete(foodLogs).where(eq(foodLogs.id,id))}
export async function saveScores(values:(typeof dailyScores.$inferInsert)[]){for(const v of values)await db.insert(dailyScores).values(v).onConflictDoUpdate({target:[dailyScores.date,dailyScores.scoreType,dailyScores.modelVersion],set:{value:v.value,confidence:v.confidence,state:v.state,inputs:v.inputs,explanation:v.explanation,updatedAt:v.updatedAt}})}
export async function getScores(type:string,days:number){return db.select().from(dailyScores).where(eq(dailyScores.scoreType,type)).orderBy(desc(dailyScores.date)).limit(days)}
export async function getScoresForDate(date:string){return db.select().from(dailyScores).where(eq(dailyScores.date,date)).orderBy(asc(dailyScores.scoreType))}
export async function saveQuality(v:typeof dataQuality.$inferInsert){return db.insert(dataQuality).values(v).onConflictDoUpdate({target:[dataQuality.date,dataQuality.dataType],set:{status:v.status,coverage:v.coverage,reason:v.reason,updatedAt:v.updatedAt}})}
export async function getQuality(date:string){return db.select().from(dataQuality).where(eq(dataQuality.date,date)).orderBy(dataQuality.dataType)}
export async function getTimeline(date:string){return db.select().from(timelineEvents).where(eq(timelineEvents.date,date)).orderBy(asc(timelineEvents.startTime))}
export async function saveTimeline(v:typeof timelineEvents.$inferInsert){return db.insert(timelineEvents).values(v).onConflictDoUpdate({target:timelineEvents.id,set:{date:v.date,eventType:v.eventType,title:v.title,startTime:v.startTime,endTime:v.endTime,source:v.source,sourceId:v.sourceId,payload:v.payload,updatedAt:v.updatedAt}})}
export async function listJournal(from?:string,to?:string){return db.select().from(journalEntries).where(from&&to?and(gte(journalEntries.date,from),lte(journalEntries.date,to)):undefined).orderBy(desc(journalEntries.date),desc(journalEntries.occurredAt))}
export async function saveJournal(v:typeof journalEntries.$inferInsert){return (await db.insert(journalEntries).values(v).returning())[0]}
export async function deleteJournal(id:string){return db.delete(journalEntries).where(eq(journalEntries.id,id))}
export async function listStrength(limit=50){const sessions=await db.select().from(strengthSessions).orderBy(desc(strengthSessions.date),desc(strengthSessions.startTime)).limit(limit),sets=await db.select().from(strengthSets);return sessions.map(session=>({...session,sets:sets.filter(set=>set.sessionId===session.id)}))}
export async function saveStrength(session:typeof strengthSessions.$inferInsert,sets:(typeof strengthSets.$inferInsert)[]){return db.transaction(async tx=>{const saved=(await tx.insert(strengthSessions).values(session).returning())[0];if(sets.length)await tx.insert(strengthSets).values(sets);return {...saved,sets}})}
export async function deleteStrength(id:string){return db.transaction(async tx=>{await tx.delete(strengthSets).where(eq(strengthSets.sessionId,id));await tx.delete(strengthSessions).where(eq(strengthSessions.id,id))})}
export async function saveCoachMessage(threadId:string,role:string,content:string,citations:unknown[]=[]){const now=Date.now();await db.insert(coachThreads).values({id:threadId,title:'Health coach',createdAt:now,updatedAt:now}).onConflictDoUpdate({target:coachThreads.id,set:{updatedAt:now}});return (await db.insert(coachMessages).values({id:crypto.randomUUID(),threadId,role,content,citations,createdAt:now}).returning())[0]}
export async function getCoachMessages(threadId:string,limit=30){return db.select().from(coachMessages).where(eq(coachMessages.threadId,threadId)).orderBy(desc(coachMessages.createdAt)).limit(limit).then(rows=>rows.reverse())}
export async function createWriteOperation(dataType:string,method:string,request:unknown){const now=Date.now(),id=crypto.randomUUID();await db.insert(writeOperations).values({id,dataType,method,status:'pending',request:request as object,createdAt:now,updatedAt:now});return id}
export async function finishWriteOperation(id:string,status:string,response?:unknown,error?:string){await db.update(writeOperations).set({status,response:response as object|undefined,error,updatedAt:Date.now()}).where(eq(writeOperations.id,id))}
