import 'server-only';
import { accessToken } from './oauth';
import { endpoints } from './config';

const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function request(path:string,init:RequestInit={},attempt=0):Promise<any>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(`${endpoints.health}${path}`,{...init,signal:controller.signal,headers:{Authorization:`Bearer ${await accessToken()}`,Accept:'application/json','Content-Type':'application/json',...(init.headers??{})},cache:'no-store'});if((r.status===429||r.status>=500)&&attempt<3){await wait(2**attempt*1000);return request(path,init,attempt+1)}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(`Health API ${r.status}: ${JSON.stringify(d)}`);return d}finally{clearTimeout(timer)}}
export const identity=()=>request('/users/me/identity');
export async function listDataPoints(type:string,filter?:string,pageSize=1000){const all:any[]=[];let page='';do{const qs=new URLSearchParams({page_size:String(type==='sleep'||type==='exercise'?25:pageSize)});if(filter)qs.set('filter',filter);if(page)qs.set('page_token',page);const d=await request(`/users/me/dataTypes/${type}/dataPoints?${qs}`);all.push(...(d.dataPoints??[]));page=d.nextPageToken??''}while(page);return all}
const civil=(d:Date,h:number,m=0,s=0)=>({date:{year:d.getFullYear(),month:d.getMonth()+1,day:d.getDate()},time:{hours:h,minutes:m,seconds:s,nanos:0}});
export async function dailyRollup(type:string,start:Date,end:Date){const all:any[]=[];let cursor=new Date(start);while(cursor<=end){const chunkEnd=new Date(cursor);chunkEnd.setDate(chunkEnd.getDate()+13);if(chunkEnd>end)chunkEnd.setTime(end.getTime());const d=await request(`/users/me/dataTypes/${type}/dataPoints:dailyRollUp`,{method:'POST',body:JSON.stringify({range:{start:civil(cursor,0),end:civil(chunkEnd,23,59,59)},windowSizeDays:1})});all.push(...(d.rollupDataPoints??[]));cursor=new Date(chunkEnd);cursor.setDate(cursor.getDate()+1)}return all}
