import 'server-only';
import {getDaily,getExercises,getHealthCoverage,getHealthRecords} from './db';
import type {Exercise,HealthRecord,Metric} from '../types';

export type SleepSession={id:string;date:string|null;startTime:string|null;endTime:string|null;minutesAsleep:number|null;minutesAwake:number|null;minutesInSleepPeriod:number|null;minutesToFallAsleep:number|null;minutesAfterWakeUp:number|null;stages:{awake:number;light:number;deep:number;rem:number}};
export type VitalPoint={id:string;date:string|null;time:string|null;value:number|null;unit:string;source:string};
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:null};
const inner=(payload:any)=>Object.entries(payload??{}).find(([key,value])=>!['name','dataSource'].includes(key)&&value&&typeof value==='object')?.[1]??payload;
function sleepSession(row:any):SleepSession{const p:any=inner(row.payload),s=p.summary??{},interval=p.interval??{},stages={awake:0,light:0,deep:0,rem:0};for(const stage of s.stagesSummary??[]){const key=String(stage.type??'').toLowerCase() as keyof typeof stages;if(key in stages)stages[key]+=n(stage.minutes)??0}const start=interval.startTime??row.startTime,end=interval.endTime??row.endTime;return{id:row.id,date:row.date??start?.slice(0,10)??null,startTime:start??null,endTime:end??null,minutesAsleep:n(s.minutesAsleep),minutesAwake:n(s.minutesAwake),minutesInSleepPeriod:n(s.minutesInSleepPeriod),minutesToFallAsleep:n(s.minutesToFallAsleep),minutesAfterWakeUp:n(s.minutesAfterWakeUp),stages}}
function vitalPoint(row:any,unit:string):VitalPoint{const p:any=inner(row.payload);const value=row.numericValue??n(p.averageHeartRateVariabilityMilliseconds??p.dailyAverageHeartRateVariabilityMilliseconds??p.breathsPerMinute??p.beatsPerMinute??p.percentage??p.value??p.average);return{id:row.id,date:row.date??row.startTime?.slice(0,10)??null,time:row.startTime??null,value,unit,source:p?.dataSource?.platform??'FITBIT'}}
export async function getSleepData(limit=90){const rows=await getHealthRecords('sleep',limit);const sessions=rows.map(sleepSession);return{sessions,latest:sessions[0]??null,trend:sessions.slice().reverse().map(s=>({date:s.date,value:s.minutesAsleep}))}}
export async function getVitals(){const specs=[['daily-resting-heart-rate','bpm'],['daily-heart-rate-variability','ms'],['daily-oxygen-saturation','%'],['daily-respiratory-rate','/min'],['daily-sleep-temperature-derivations','variation'],['daily-vo2-max','VO₂']];const result:Record<string,VitalPoint[]>={};for(const [type,unit] of specs)result[type]= (await getHealthRecords(type,90)).map(row=>vitalPoint(row,unit));result['heart-rate']=(await getHealthRecords('heart-rate',500)).filter(row=>row.startTime||row.date).map(row=>vitalPoint(row,'bpm'));result['heart-rate-variability']=(await getHealthRecords('heart-rate-variability',90)).filter(row=>row.startTime||row.date).map(row=>vitalPoint(row,'ms'));return result}
export async function getActivityData(days=90){const metricNames=['steps','active-zone-minutes','active-minutes','total-calories','active-energy-burned','distance','floors'];const metrics:Record<string,Metric[]>={};for(const metric of metricNames)metrics[metric]=await getDaily(metric,days);return{metrics,exercises:await getExercises(100)}}
export async function getDataExplorer(){const [coverage,syncStates]=await Promise.all([getHealthCoverage(),(await import('./db')).getSyncStates()]);return{coverage,syncStates}}
