import 'server-only';
import {getDaily,getFoodLogs,getHealthRecords,listJournal,listStrength,saveQuality,saveScores} from './db';
import type {DailyScore,DataQuality,ScoreContribution} from '../types';

export const SCORE_VERSION='wellness-v1.0.0';
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const inner=(payload:any)=>Object.entries(payload??{}).find(([key,value])=>!['name','dataSource'].includes(key)&&value&&typeof value==='object')?.[1] as any??payload;
const mean=(a:number[])=>a.length?a.reduce((s,n)=>s+n,0)/a.length:null;
const median=(a:number[])=>{if(!a.length)return null;const x=[...a].sort((p,q)=>p-q),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const robust=(value:number|null,values:number[],higher=true)=>{const base=median(values);if(value==null||base==null)return {base,z:0};const deviations=values.map(x=>Math.abs(x-base)),mad=median(deviations)??0,scale=Math.max(mad*1.4826,Math.abs(base)*.05,1),z=clamp((value-base)/scale,-2.5,2.5)*(higher?1:-1);return{base,z}};
const dateMinus=(date:string,days:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10)};
const recordValue=(row:any)=>{const p=inner(row.payload);return row.numericValue??num(p?.averageHeartRateVariabilityMilliseconds??p?.dailyAverageHeartRateVariabilityMilliseconds??p?.breathsPerMinute??p?.beatsPerMinute??p?.percentage??p?.value??p?.average??p?.variation)};
const contribution=(key:string,label:string,value:number|null,baseline:number|null,impact:number,unit:string):ScoreContribution=>({key,label,value,baseline,impact:Math.round(impact),unit,status:value==null?'missing':impact>.25?'positive':impact<-.25?'negative':'neutral'});

async function signal(type:string,date:string){const rows=await getHealthRecords(type,120);const points=rows.map(r=>({date:r.date??r.startTime?.slice(0,10)??'',value:recordValue(r)})).filter(x=>x.date&&x.value!=null) as {date:string;value:number}[];return{today:points.find(x=>x.date===date)?.value??null,history:points.filter(x=>x.date<date&&x.date>=dateMinus(date,60)).map(x=>x.value)}}
async function sleepSignals(date:string){const rows=await getHealthRecords('sleep',120),sessions=rows.map(row=>{const p=inner(row.payload),s=p?.summary??{},start=p?.interval?.startTime??row.startTime,d=row.date??start?.slice(0,10)??'';return{date:d,minutes:num(s.minutesAsleep),period:num(s.minutesInSleepPeriod),awake:num(s.minutesAwake),start}}).filter(x=>x.date);return{today:sessions.find(x=>x.date===date),history:sessions.filter(x=>x.date<date&&x.date>=dateMinus(date,60)&&x.minutes!=null)}}
async function activitySignal(metric:string,date:string){const rows=await getDaily(metric,90),today=rows.find(x=>x.date===date)?.value??null,history=rows.filter(x=>x.date<date&&x.date>=dateMinus(date,60)).map(x=>x.value).filter((x):x is number=>x!=null);return{today,history}}
function state(historyCount:number,present:number,needed:number){if(present<needed)return'insufficient' as const;return historyCount>=21?'ready' as const:'calibrating' as const}
function confidence(present:number,total:number,history:number){if(present===total&&history>=28)return'high' as const;if(present>=Math.ceil(total*.6)&&history>=14)return'medium' as const;return'low' as const}

export async function computeScores(date=new Date().toISOString().slice(0,10)):Promise<DailyScore[]>{
  const [hrv,rhr,resp,spo2,temp,sleep,steps,azm,energy]=await Promise.all([signal('daily-heart-rate-variability',date),signal('daily-resting-heart-rate',date),signal('daily-respiratory-rate',date),signal('daily-oxygen-saturation',date),signal('daily-sleep-temperature-derivations',date),sleepSignals(date),activitySignal('steps',date),activitySignal('active-zone-minutes',date),activitySignal('active-energy-burned',date)]);
  const recoveryInputs=[['hrv','HRV',hrv,true,'ms'],['rhr','Resting heart rate',rhr,false,'bpm'],['resp','Respiratory rate',resp,false,'/min'],['spo2','Blood oxygen',spo2,true,'%'],['temp','Temperature deviation',temp,false,'°']] as const;
  let recoveryValue=50,weight=0;const recoveryContributions:ScoreContribution[]=[];for(const [key,label,s,higher,unit] of recoveryInputs){const r=robust(s.today,s.history,higher),w=key==='hrv'||key==='rhr'?1.5:1;if(s.today!=null){recoveryValue+=r.z*8*w;weight+=w}recoveryContributions.push(contribution(key,label,s.today,r.base,r.z*w,unit))}
  const recoveryPresent=recoveryInputs.filter(([, ,s])=>s.today!=null).length,recoveryHistory=Math.min(...recoveryInputs.filter(([, ,s])=>s.history.length).map(([, ,s])=>s.history.length),0)||Math.max(...recoveryInputs.map(([, ,s])=>s.history.length));
  const sleepToday=sleep.today,sleepMinutes=sleepToday?.minutes??null,sleepHistory=sleep.history.map(x=>x.minutes!).filter((x):x is number=>x!=null),sleepBase=median(sleepHistory),durationScore=sleepMinutes==null?null:clamp(100-Math.abs(480-sleepMinutes)/3.5),efficiency=sleepToday?.minutes!=null&&sleepToday.period?clamp(sleepToday.minutes/sleepToday.period*100):null,continuity=sleepToday?.awake!=null&&sleepToday.period?clamp(100-sleepToday.awake/sleepToday.period*100):null,sleepValue=mean([durationScore,efficiency,continuity].filter((x):x is number=>x!=null));
  const [strainSteps,strainAzm,strainEnergy]=[robust(steps.today,steps.history,true),robust(azm.today,azm.history,true),robust(energy.today,energy.history,true)],strainPresent=[steps.today,azm.today,energy.today].filter(x=>x!=null).length,strainValue=strainPresent?clamp(45+strainSteps.z*8+strainAzm.z*13+strainEnergy.z*9):null;
  const stressPresent=[rhr.today,hrv.today,steps.today].filter(x=>x!=null).length,stressValue=stressPresent>=2?clamp(50-robust(hrv.today,hrv.history,true).z*12+robust(rhr.today,rhr.history,true).z*12+Math.max(0,robust(steps.today,steps.history,true).z)*4):null;
  const energyValue=recoveryPresent>=2?clamp((clamp(recoveryValue)+(sleepValue??50)+(100-(strainValue??50))+(100-(stressValue??50)))/4):null;
  const history=Math.max(hrv.history.length,rhr.history.length,sleepHistory.length,steps.history.length),make=(type:DailyScore['type'],value:number|null,present:number,total:number,contributions:ScoreContribution[],summary:string):DailyScore=>({date,type,value:state(history,present,Math.ceil(total*.5))==='ready'&&value!=null?Math.round(value):null,confidence:confidence(present,total,history),state:state(history,present,Math.ceil(total*.5)),modelVersion:SCORE_VERSION,contributions,summary});
  const scores=[
    make('recovery',clamp(recoveryValue),recoveryPresent,5,recoveryContributions,'Readiness from overnight signals versus your personal baseline.'),
    make('sleep',sleepValue,[sleepMinutes,efficiency,continuity].filter(x=>x!=null).length,3,[contribution('duration','Sleep duration',sleepMinutes,sleepBase,durationScore==null?0:(durationScore-50)/20,'min'),contribution('efficiency','Sleep efficiency',efficiency,85,efficiency==null?0:(efficiency-85)/8,'%'),contribution('continuity','Sleep continuity',continuity,90,continuity==null?0:(continuity-90)/8,'%')],'Sleep sufficiency, efficiency, and continuity.'),
    make('strain',strainValue,strainPresent,3,[contribution('steps','Steps',steps.today,strainSteps.base,strainSteps.z,'steps'),contribution('azm','Zone minutes',azm.today,strainAzm.base,strainAzm.z,'min'),contribution('energy','Active energy',energy.today,strainEnergy.base,strainEnergy.z,'kcal')],'Daily exertion relative to your normal activity.'),
    make('stress',stressValue,stressPresent,3,[contribution('hrv','HRV',hrv.today,median(hrv.history),robust(hrv.today,hrv.history,true).z,'ms'),contribution('rhr','Resting heart rate',rhr.today,median(rhr.history),-robust(rhr.today,rhr.history,false).z,'bpm'),contribution('movement','Movement',steps.today,median(steps.history),robust(steps.today,steps.history,true).z,'steps')],'Physiological load estimate; not a measure of mental health.'),
    make('energy',energyValue,[recoveryPresent>=2,sleepValue!=null,strainValue!=null,stressValue!=null].filter(Boolean).length,4,[],'Recovery and sleep recharge; strain and physiological stress drain.')
  ];
  await saveScores(scores.map(s=>({date:s.date,scoreType:s.type,modelVersion:s.modelVersion,value:s.value,confidence:s.confidence,state:s.state,inputs:s.contributions,explanation:{summary:s.summary},updatedAt:Date.now()})));
  const quality:DataQuality[]=[['recovery',recoveryPresent,5],['sleep',sleepToday?1:0,1],['activity',strainPresent,3]].map(([dataType,present,total])=>({date,dataType:String(dataType),status:Number(present)===Number(total)?'good':Number(present)>0?'partial':'missing',coverage:Number(present)/Number(total),reason:Number(present)===Number(total)?null:'Some source signals are unavailable.'})) as DataQuality[];
  await Promise.all(quality.map(q=>saveQuality({...q,updatedAt:Date.now()})));
  return scores;
}
export async function computeScoreRange(days=30){const end=new Date(),dates:string[]=[];for(let i=Math.min(90,Math.max(1,days))-1;i>=0;i--){const d=new Date(end);d.setDate(end.getDate()-i);dates.push(d.toISOString().slice(0,10))}for(const date of dates)await computeScores(date);return dates.length}

export async function journalInsights(){const entries=await listJournal(),scores=await (await import('./db')).getScores('recovery',365),byDate=new Map(scores.map(x=>[x.date,x.value])),groups=new Map<string,{yes:number[];no:number[]}>();for(const entry of entries){const score=byDate.get(entry.date);if(score==null)continue;const x=groups.get(entry.habit)??{yes:[],no:[]};String(entry.value).toLowerCase()==='yes'?x.yes.push(score):x.no.push(score);groups.set(entry.habit,x)}return [...groups].map(([habit,x])=>{const ready=x.yes.length>=5&&x.no.length>=5,effect=ready?(mean(x.yes)!-mean(x.no)!):null;return{habit,yes:x.yes.length,no:x.no.length,ready,effect:effect==null?null:Math.round(effect*10)/10,metric:'recovery',note:ready?`Associated recovery difference: ${effect!>=0?'+':''}${Math.round(effect!*10)/10} points. Correlation is not causation.`:'Log at least 5 yes and 5 no days with Recovery scores.'}})}

export async function nutritionSummary(date:string){const rows=await getFoodLogs(date);return rows.reduce((a,x)=>({calories:a.calories+(x.calories??0),proteinG:a.proteinG+(x.proteinG??0),carbsG:a.carbsG+(x.carbsG??0),fatG:a.fatG+(x.fatG??0),entries:a.entries+1}),{calories:0,proteinG:0,carbsG:0,fatG:0,entries:0})}

export async function strengthSummary(){const sessions=await listStrength(30);return{sessions:sessions.length,volumeKg:sessions.flatMap(x=>x.sets).reduce((sum,set)=>sum+(set.loadKg??0)*(set.reps??0),0)}}
