import 'server-only';
import { config } from './config';
import { dailyRollup, identity, listDataPoints } from './health';
import { saveDailyMetrics, saveExercises, saveHealthRecords, setMeta, setSyncState } from './db';

const rollupMetrics=['steps','distance','active-zone-minutes','active-minutes','total-calories','active-energy-burned','altitude','calories-in-heart-rate-zone','floors','run-vo2-max','sedentary-period','swim-lengths-data','time-in-heart-rate-zone'];
const recordTypes=['activity-level','blood-glucose','body-fat','core-body-temperature','daily-heart-rate-variability','daily-heart-rate-zones','daily-oxygen-saturation','daily-respiratory-rate','daily-resting-heart-rate','daily-sleep-temperature-derivations','daily-vo2-max','electrocardiogram','heart-rate','heart-rate-variability','height','hydration-log','irregular-rhythm-notification','nutrition-log','oxygen-saturation','respiratory-rate-sleep-summary','run-vo2-max','sleep','vo2-max','weight','food','food-measurement-unit'];
const intervalTypes=new Set(['activity-level','active-energy-burned','active-minutes','active-zone-minutes','altitude','calories-in-heart-rate-zone','distance','floors','sedentary-period','steps','swim-lengths-data','time-in-heart-rate-zone']);
const dailyTypes=new Set(recordTypes.filter(x=>x.startsWith('daily-')));
const sampleTypes=new Set(['blood-glucose','body-fat','core-body-temperature','heart-rate','heart-rate-variability','height','nutrition-log','oxygen-saturation','respiratory-rate-sleep-summary','weight','food']);
const unfilterableTypes=new Set(['food','food-measurement-unit','hydration-log','nutrition-log']);
const highVolumeTypes=new Set(['activity-level','heart-rate','food','food-measurement-unit','hydration-log','nutrition-log']);
const endDate=(d:Date)=>{const x=new Date(d);x.setDate(x.getDate()+1);return x.toISOString().slice(0,10)};
const snake=(type:string)=>type.replaceAll('-','_');
function filterFor(type:string,start:Date,end:Date){const from=start.toISOString().slice(0,10),to=endDate(end),name=snake(type);if(unfilterableTypes.has(type))return undefined;if(dailyTypes.has(type))return `${name}.date >= "${from}" AND ${name}.date < "${to}"`;if(sampleTypes.has(type))return `${name}.sample_time.civil_time >= "${from}" AND ${name}.sample_time.civil_time < "${to}"`;if(type==='electrocardiogram')return `electrocardiogram.interval.start_time >= "${from}T00:00:00Z"`;if(type==='sleep')return `sleep.interval.civil_end_time >= "${from}" AND sleep.interval.civil_end_time < "${to}"`;if(type==='exercise'||intervalTypes.has(type))return `${name}.interval.civil_start_time >= "${from}" AND ${name}.interval.civil_start_time < "${to}"`;return undefined}
const number=(v:any):number|null=>{if(v==null)return null;if(typeof v==='object'){for(const k of ['countSum','sum','total','average','avg','value','bpm','beatsPerMinute','percentage','millimeters','millis'])if(v[k]!=null)return number(v[k])}const n=Number(v);return Number.isFinite(n)?n:null};
const payloadOf=(p:any)=>Object.entries(p??{}).find(([key,value])=>!['name','dataSource'].includes(key)&&value&&typeof value==='object')?.[1]??p;
const dateOf=(p:any)=>{const n:any=payloadOf(p),d=n?.civilStartTime?.date??n?.interval?.civilStartTime?.date??n?.sampleTime?.civilTime?.date??n?.date;if(d)return `${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`;const time=timeOf(p);return typeof time==='string'?time.slice(0,10):null};
const timeOf=(p:any)=>{const n:any=payloadOf(p);return n?.interval?.startTime??n?.sampleTime?.physicalTime??n?.startTime??n?.session?.startTime??null};
const numericOf=(p:any)=>{const n:any=payloadOf(p);for(const key of ['value','count','average','mean','bpm','beatsPerMinute','breathsPerMinute','percentage','millimeters','millis','averageHeartRateVariabilityMilliseconds','dailyAverageHeartRateVariabilityMilliseconds']){const v=number(n?.[key]);if(v!=null)return v}return null};
const idOf=(type:string,p:any)=>{const name=p?.name;return name&&!name.endsWith('/')?`${type}:${name}`:`${type}:${name??''}:${timeOf(p)??dateOf(p)??JSON.stringify(p).slice(0,200)}`};
const durationSeconds=(value:any)=>{if(value==null)return null;if(typeof value==='number')return Math.round(value);const match=String(value).match(/([\d.]+)s/);return match?Math.round(Number(match[1])):null};
async function limited<T>(items:string[],limit:number,work:(item:string)=>Promise<T>){const results:T[]=[];let cursor=0;async function worker(){while(cursor<items.length){const item=items[cursor++];results.push(await work(item))}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return results}

export async function runSync(days=config.syncDays,options:{full?:boolean}={}){
  const end=new Date(),start=new Date(end);start.setDate(end.getDate()-days+1);const result:any={days,metrics:{},records:{},exercises:0,errors:[],startedAt:Date.now()};
  const full=options.full??process.env.SYNC_RAW_TYPES==='true';
  try{const id=await identity();if(id.healthUserId)await setMeta('healthUserId',id.healthUserId)}catch(e){result.errors.push(`identity: ${(e as Error).message}`)}
  await limited(rollupMetrics,4,async metric=>{await setSyncState(metric,'running');try{const rows:{date:string;metric:string;value:number;updatedAt:number}[]=[];for(const p of await dailyRollup(metric,start,end)){const d=p.civilStartTime?.date,key=metric.replace(/-([a-z])/g,(_,c)=>c.toUpperCase()),value=number(p[key]??p[metric]??Object.values(p).find((v:any)=>v&&typeof v==='object'&&!v.date));if(d&&value!=null)rows.push({date:`${d.year}-${String(d.month).padStart(2,'0')}-${String(d.day).padStart(2,'0')}`,metric,value,updatedAt:Date.now()})}await saveDailyMetrics(rows);result.metrics[metric]=rows.length;await setSyncState(metric,'complete',rows.length)}catch(e){result.metrics[metric]=0;result.errors.push(`${metric}: ${(e as Error).message}`);await setSyncState(metric,'error',0,(e as Error).message)}});
  const recordsToSync=full?recordTypes:recordTypes.filter(type=>!highVolumeTypes.has(type));for(const type of recordTypes.filter(type=>!recordsToSync.includes(type))){result.records[type]=0;await setSyncState(type,'skipped',0,'Skipped in normal sync; use full sync for raw/high-volume records.')}
  await limited(recordsToSync,3,async type=>{await setSyncState(type,'running');try{const rows:any[]=[];for(const p of await listDataPoints(type,filterFor(type,start,end))){rows.push({id:idOf(type,p),dataType:type,startTime:timeOf(p),endTime:p?.endTime??p?.interval?.endTime??null,date:dateOf(p),numericValue:numericOf(p),payload:p,updatedAt:Date.now()})}await saveHealthRecords(rows);result.records[type]=rows.length;await setSyncState(type,'complete',rows.length)}catch(e){result.records[type]=0;result.errors.push(`${type}: ${(e as Error).message}`);await setSyncState(type,'error',0,(e as Error).message)}});
  try{await setSyncState('exercise','running');const filter=filterFor('exercise',start,end),rows:any[]=[];for(const p of await listDataPoints('exercise',filter)){const x=p.exercise??{},m=x.metricsSummary??{};rows.push({id:p.name?.split('/').pop()??crypto.randomUUID(),type:x.exerciseType,displayName:x.displayName,startTime:x.interval?.startTime,durationS:durationSeconds(x.activeDuration),calories:number(m.caloriesKcal),distanceMm:number(m.distanceMillimiters??m.distanceMillimeters),steps:number(m.steps),avgHr:number(m.averageHeartRateBeatsPerMinute),raw:p,updatedAt:Date.now()})}await saveExercises(rows);result.exercises=rows.length;await setSyncState('exercise','complete',rows.length)}catch(e){result.errors.push(`exercise: ${(e as Error).message}`);await setSyncState('exercise','error',0,(e as Error).message)}
  await setMeta('lastSync',Date.now());result.finishedAt=Date.now();return result;
}

export async function syncDataType(type:string,days=7){if(!recordTypes.includes(type)&&type!=='exercise')throw Error(`Unsupported data type: ${type}`);const end=new Date(),start=new Date(end);start.setDate(end.getDate()-days+1);const rows:any[]=[];for(const p of await listDataPoints(type,filterFor(type,start,end))){rows.push({id:idOf(type,p),dataType:type,startTime:timeOf(p),endTime:p?.endTime??p?.interval?.endTime??null,date:dateOf(p),numericValue:numericOf(p),payload:p,updatedAt:Date.now()})}await saveHealthRecords(rows);await setSyncState(type,'complete',rows.length);return rows.length}
