'use client';
import { useEffect, useState } from 'react';

type Metric={date:string;value:number}; type Exercise={start_time?:string;display_name?:string;type?:string;duration_s?:number;calories?:number;distance_mm?:number;avg_hr?:number};
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080';
async function get<T>(path:string):Promise<T>{const r=await fetch(`${API}${path}`);if(!r.ok)throw Error(`${r.status} ${path}`);return r.json();}
const avg=(a:Metric[])=>a.length?Math.round(a.reduce((s,x)=>s+x.value,0)/a.length):0;const km=(x:number)=>(x/1_000_000).toFixed(2)+' km';
function Chart({data,color}:{data:Metric[];color:string}){const max=Math.max(...data.map(x=>x.value),1);return <div className="chart">{data.map(x=><div className="bar" key={x.date}><div className="barValue" style={{height:`${Math.max(3,x.value/max*100)}%`,background:color}}/><small>{x.date.slice(5)}</small></div>)}</div>}
export default function Home(){const [status,setStatus]=useState<any>();const [steps,setSteps]=useState<Metric[]>([]);const [azm,setAzm]=useState<Metric[]>([]);const [cals,setCals]=useState<Metric[]>([]);const [dist,setDist]=useState<Metric[]>([]);const [exercises,setExercises]=useState<Exercise[]>([]);const [error,setError]=useState('');const [syncing,setSyncing]=useState(false);
 const load=async()=>{try{const s=await get<any>('/api/status');setStatus(s);if(s.authenticated){const [a,b,c,d,e]=await Promise.all([get<Metric[]>('/api/daily?metric=steps&days=30'),get<Metric[]>('/api/daily?metric=active-zone-minutes&days=30'),get<Metric[]>('/api/daily?metric=total-calories&days=30'),get<Metric[]>('/api/daily?metric=distance&days=30'),get<Exercise[]>('/api/exercises?limit=25')]);setSteps(a);setAzm(b);setCals(c);setDist(d);setExercises(e)}}catch(e){setError((e as Error).message)}};
 useEffect(()=>{load()},[]);const sync=async()=>{setSyncing(true);setError('');try{await fetch(`${API}/api/sync`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load()}catch(e){setError((e as Error).message)}finally{setSyncing(false)}};
 if(!status)return <main><p>Loading…</p></main>;if(!status.authenticated)return <main><section className="card center"><h1>Fitbit Air <span>dashboard</span></h1><h2>Not connected</h2><p>Connect your Google/Fitbit account to pull activity data.</p><a className="button primary" href={`${API}/auth/login`}>Connect Fitbit</a></section></main>;
 return <main><header><h1>Fitbit Air <span>dashboard</span></h1><div><small>{status.lastSync?`Last sync ${new Date(status.lastSync).toLocaleString()}`:'Not synced'}</small><button onClick={sync} disabled={syncing}>{syncing?'Syncing…':'Sync now'}</button></div></header>{error&&<p className="error">{error}</p>}<section className="stats"><div><small>Avg daily steps</small><strong>{avg(steps).toLocaleString()}</strong></div><div><small>Avg zone minutes</small><strong>{avg(azm).toLocaleString()}</strong></div><div><small>Avg calories</small><strong>{avg(cals).toLocaleString()}</strong></div><div><small>Total distance</small><strong>{km(dist.reduce((s,x)=>s+x.value,0))}</strong></div></section><section className="card"><h2>Steps</h2><Chart data={steps} color="#4f9dff"/></section><section className="card"><h2>Active Zone Minutes</h2><Chart data={azm} color="#37d67a"/></section><section className="card"><h2>Recent workouts</h2><table><thead><tr><th>Date</th><th>Type</th><th>Duration</th><th>Cal</th><th>Distance</th><th>Avg HR</th></tr></thead><tbody>{exercises.map((e,i)=><tr key={i}><td>{e.start_time?new Date(e.start_time).toLocaleDateString():'—'}</td><td>{e.display_name||e.type||'—'}</td><td>{e.duration_s?Math.round(e.duration_s/60)+' min':'—'}</td><td>{e.calories??'—'}</td><td>{e.distance_mm?km(e.distance_mm):'—'}</td><td>{e.avg_hr??'—'}</td></tr>)}</tbody></table></section></main>}
