import { Head, useForm } from '@inertiajs/react';
import { Button, Empty, ErrorState, PageHeader, Section } from '../../components/ui';
import type { StrengthSession } from '../../types';
export default function Strength({sessions=[]}:{sessions:StrengthSession[]}){
    const form=useForm({date:new Date().toISOString().slice(0,10),title:'Strength workout',exercise:'Squat',reps:'8',loadKg:''});
    const submit=(e:React.FormEvent)=>{e.preventDefault();form.transform(x=>({date:x.date,title:x.title,sets:[{exercise:x.exercise,reps:x.reps,loadKg:x.loadKg}]}));form.post('/dashboard/strength',{preserveScroll:true,onSuccess:()=>form.reset('loadKg')})};
    const volume=sessions.flatMap(x=>x.sets).reduce((s,x)=>s+(x.loadKg??0)*(x.reps??0),0);
    return <><Head title="Strength"/><main><PageHeader eyebrow="Training" title="Strength" subtitle="Sets, reps, load, progression, and muscular work."/><ErrorState message={Object.values(form.errors)[0]}/><section className="metricGrid"><div className="metricCard"><span>Sessions</span><strong>{sessions.length}</strong><span>Recent</span></div><div className="metricCard"><span>Volume</span><strong>{Math.round(volume)}<small> kg</small></strong><span>Load × reps</span></div></section><Section title="Quick log"><form className="wellnessForm" onSubmit={submit}><label>Session<input value={form.data.title} onChange={e=>form.setData('title',e.target.value)}/></label><label>Exercise<input value={form.data.exercise} onChange={e=>form.setData('exercise',e.target.value)}/></label><label>Reps<input inputMode="numeric" value={form.data.reps} onChange={e=>form.setData('reps',e.target.value)}/></label><label>Load kg<input inputMode="decimal" value={form.data.loadKg} onChange={e=>form.setData('loadKg',e.target.value)}/></label><Button type="submit" disabled={form.processing}>Save set</Button></form></Section><Section title="History">{sessions.length?<div className="activityList">{sessions.map(x=><div className="activityRow" key={x.id}><span className="activityDot">●</span><div><strong>{x.title}</strong><small>{x.date} · {x.sets.map(s=>`${s.exercise} ${s.reps??'—'}×${s.loadKg??0}kg`).join(', ')}</small></div></div>)}</div>:<Empty>No strength sessions.</Empty>}</Section></main></>;
}
